[package]
name = "osdash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.9.0"
sys-info = "0.9.1"
sysinfo = "0.25.3"
